name: Test

on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ['3.10']
        tox_env: [orange-released]
        pyqt: ['5.15.*', '6.6.*']
        experimental: [false]
        include:
          - os: windows-latest
            python-version: '3.9'
            tox_env: orange-oldest
            pyqt: '5.15.*'
            experimental: false
          - os: macOS-latest
            python-version: '3.9'
            tox_env: orange-oldest
            pyqt: '5.15.*'
            experimental: false
          - os: ubuntu-latest
            python-version: '3.9'
            tox_env: orange-oldest
            pyqt: '5.15.*'
            experimental: false

          - os: windows-latest
            python-version: '3.11'
            tox_env: orange-latest
            pyqt: '5.15.*'
            experimental: false
          - os: macOS-latest
            python-version: '3.11'
            tox_env: orange-latest
            pyqt: '5.15.*'
            experimental: false
          - os: ubuntu-latest
            python-version: '3.11'
            tox_env: orange-latest
            pyqt: '5.15.*'
            experimental: false
    uses: ./.github/workflows/test-job.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      tox_env: ${{ matrix.tox_env }}
      pyqt: ${{ matrix.pyqt }}
      experimental: ${{ matrix.experimental }}
